// Maps a `videos.playlist` slug (see supabase/migrations/0007_...) to how
// it's presented on the site. Add an entry here whenever a new playlist
// slug is introduced on the automation side.
//
// type: "rolling" playlists (like top-news) are the recency-driven daily
//   feed and aren't listed on courses.html. "course" playlists are browsable
//   there and get their own course.html page.
// ordered: true means the playlist has a meaningful idx (episode order),
//   so course.html shows an episode number badge on each card instead of
//   a view count.
// region/language: unlike tier/department/subject below, these mirror real
//   columns on the videos table (see migration 0011/0012): every course's
//   videos were already seeded with the {global}/"en" default, which is
//   accurate for all of them (no current course is region-specific
//   content). Listed here anyway as reference for whoever seeds a new
//   course later, so its rows get tagged consistently with its source.
//   Omitted for "top-news": that playlist's region genuinely varies by
//   channel (see top-news/channels.ts), so no single value belongs here.
// tier/department/subject: the Anchor Academy taxonomy (see
//   flo/2608-anchor/docs/260822-course-taxonomy-playlist-candidates.md).
//   Config-layer only, no DB schema involved: `category` on the videos
//   table already doubles as "Subject" and `playlist` as "Course", so this
//   is purely a display-grouping hint for courses.html/course.html.
//   Omitted for "rolling" playlists, which sit outside the tier ladder.

// Tier ladder, in display order. Extracurricular sits parallel to the
// academic ladder rather than being a "level" of it.
window.ANCHOR_TIERS = [
  { key: "fundamental", displayName: "Fundamental", icon: "spa" },
  { key: "standard", displayName: "Standard", icon: "menu_book" },
  { key: "advanced", displayName: "Advanced", icon: "engineering" },
  { key: "expert", displayName: "Expert", icon: "workspace_premium" },
  { key: "extracurricular", displayName: "Extracurricular", icon: "sports_esports" },
  { key: "entertainment", displayName: "Entertainment", icon: "movie" },
  { key: "miscellaneous", displayName: "Miscellaneous", icon: "apps" },
];

// Tiers with no fixed academic promise: courses.html skips the
// locked/"coming soon" placeholder treatment for these (see INFORMAL_TIERS
// there), same as extracurricular already did before this list existed.
window.ANCHOR_INFORMAL_TIERS = ["extracurricular", "entertainment", "miscellaneous"];

// Departments, keyed for lookup from a course entry's `department` field.
window.ANCHOR_DEPARTMENTS = {
  humanities: { displayName: "Humanities", icon: "account_balance" },
  sciences: { displayName: "Sciences", icon: "science" },
  stem: { displayName: "STEM / Engineering & Tech", icon: "precision_manufacturing" },
  "society-civics": { displayName: "Society & Civics", icon: "gavel" },
  "arts-culture": { displayName: "Arts & Culture", icon: "palette" },
  "media-literacy": { displayName: "Media & Information Literacy", icon: "fact_check" },
  // Extracurricular-only departments, informal groupings, not academic.
  "games-strategy": { displayName: "Games & Strategy", icon: "extension" },
  "tech-curiosities": { displayName: "Tech Curiosities", icon: "memory" },
  "places-culture": { displayName: "Places & Culture", icon: "public" },
  "food-culture": { displayName: "Food & Culture", icon: "restaurant" },
  "life-skills-making": { displayName: "Life Skills & Making", icon: "construction" },
  "money-finance": { displayName: "Money & Personal Finance", icon: "savings" },
  // Entertainment-only departments.
  "sports-stunts": { displayName: "Sports & Stunts", icon: "sports" },
  comedy: { displayName: "Comedy", icon: "theater_comedy" },
  "travel-adventure": { displayName: "Travel & Adventure", icon: "flight_takeoff" },
  documentaries: { displayName: "Documentaries", icon: "theaters" },
  "short-films": { displayName: "Short Films", icon: "movie_filter" },
  // Miscellaneous-only departments.
  "podcasts-conversations": { displayName: "Podcasts & Conversations", icon: "podcasts" },
  storytelling: { displayName: "Storytelling", icon: "auto_stories" },
  "business-startups": { displayName: "Business & Startups", icon: "rocket_launch" },
  "health-wellness": { displayName: "Health & Wellness", icon: "self_improvement" },
};

// Departments shown under each tier, in display order. The academic ladder
// (fundamental/standard/advanced/expert) all share ACADEMIC_DEPARTMENTS and
// get the "locked, coming soon" placeholder for empty ones (see courses.html)
// since that's a fixed curriculum promise; informal tiers (see
// ANCHOR_INFORMAL_TIERS above) each get their own department list and skip
// that placeholder: a department just doesn't render if it has no courses.
const ACADEMIC_DEPARTMENTS = ["humanities", "sciences", "stem", "society-civics", "arts-culture", "media-literacy"];
window.ANCHOR_TIER_DEPARTMENTS = {
  fundamental: ACADEMIC_DEPARTMENTS,
  standard: ACADEMIC_DEPARTMENTS,
  advanced: ACADEMIC_DEPARTMENTS,
  expert: ACADEMIC_DEPARTMENTS,
  extracurricular: ["games-strategy", "tech-curiosities", "places-culture", "food-culture", "life-skills-making", "money-finance"],
  // sports-stunts leads: Entertainment exists purely for fun, so the
  // purest spectacle goes first (mirrors headlines' CATEGORY_ORDER doing
  // the opposite: fun categories trail there since that sidebar's job is
  // staying informed, not escaping).
  entertainment: ["sports-stunts", "comedy", "travel-adventure", "documentaries", "short-films"],
  miscellaneous: ["podcasts-conversations", "storytelling", "business-startups", "health-wellness"],
};

// The sitewide region/language filter's option list (see the sidebar
// filter in helpers.js). Hardcoded rather than derived from distinct
// values in the DB: only a handful of codes are in real use across all
// sources (top-news/channels.ts, rss-headlines/feeds.ts, the course
// entries below), so a fixed list is simpler than a live query. Add a new
// entry here whenever a source using a new code gets added.
window.ANCHOR_REGIONS = [
  { key: "global", displayName: "Global" },
  { key: "in", displayName: "India" },
  { key: "us", displayName: "United States" },
  { key: "eu", displayName: "Europe" },
  { key: "africa", displayName: "Africa" },
  { key: "middle-east", displayName: "Middle East" },
  { key: "asia", displayName: "Asia" },
  { key: "au", displayName: "Australia" },
  { key: "latin-america", displayName: "Latin America" },
];
window.ANCHOR_LANGUAGES = [
  { key: "en", displayName: "English" },
  { key: "hi", displayName: "Hindi" },
];

// The homepage's "which region gets its own dedicated Top News shelf"
// preference, separate from ANCHOR_REGIONS (which controls what's
// included at all). Deliberately a short, curated list rather than every
// ANCHOR_REGIONS entry: it's opt-in real estate on the homepage, not a
// filter, so it only lists regions worth a dedicated shelf for enough
// users to justify one. Add an entry here when that changes; no other code
// needs to change (see regionShelfKey/renderHomeShelves in index.html).
window.ANCHOR_HOME_REGIONS = [
  { key: "in", displayName: "India" },
  { key: "us", displayName: "United States" },
];

window.ANCHOR_PLAYLISTS = {
  "top-news": {
    displayName: "Top News",
    description: "Hourly picks from trusted news channels, judged for substance over sensationalism.",
    type: "rolling",
  },
  explainers: {
    displayName: "Explainers & Deep Dives",
    description: "Science, tech, and engineering explainers from trusted channels, updated daily.",
    type: "rolling",
  },
  business: {
    displayName: "Founder & Business",
    description: "Founder talks and business deep dives from trusted channels, updated daily.",
    type: "rolling",
  },
  talks: {
    displayName: "Idea Talks",
    description: "Single-topic talks from trusted channels, updated daily.",
    type: "rolling",
  },
  podcasts: {
    displayName: "Long-form Conversations",
    description: "Long-form interviews and conversations from trusted channels, updated daily.",
    type: "rolling",
  },

  // --- Humanities ---
  "world-history": {
    displayName: "World History",
    description: "The complete Crash Course World History series, in order.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "humanities",
    subject: "History",
  },
  "lallantop-tarikh": {
    displayName: "Tarikh: Hindi History Storytelling",
    description: "The Lallantop's Hindi-language history storytelling series, from ancient civilizations to Mughal court intrigue to modern geopolitics.",
    type: "course",
    ordered: false,
    source: "The Lallantop",
    region: ["in", "global"],
    language: "hi",
    tier: "standard",
    department: "humanities",
    subject: "History",
  },
  "world-history-2": {
    displayName: "World History 2",
    description: "The complete Crash Course World History 2 series, continuing where World History left off.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "humanities",
    subject: "History",
  },
  "black-american-history": {
    displayName: "Black American History",
    description: "Crash Course Black American History: a dedicated series on a history too often left out of the survey course.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "humanities",
    subject: "History",
  },
  "philosophy-fundamental": {
    displayName: "Philosophy for Everyday Life",
    description: "The School of Life's hand-picked take on philosophy, psychology, and self-knowledge, no jargon required.",
    type: "course",
    ordered: false,
    source: "The School of Life",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "humanities",
    subject: "Philosophy",
  },
  philosophy: {
    displayName: "Philosophy",
    description: "Crash Course Philosophy: metaphysics, epistemology, value theory, and logic.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "humanities",
    subject: "Philosophy",
  },
  literature: {
    displayName: "Literature",
    description: "Crash Course Literature, all 4 seasons: close reading and literary analysis.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "humanities",
    subject: "Literature",
  },
  "latin-american-literature": {
    displayName: "Latin American Literature",
    description: "Crash Course's tour of Latin American literary tradition, from colonial-era writing to the present.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "humanities",
    subject: "Literature",
  },
  religions: {
    displayName: "Religions",
    description: "Crash Course Religions: a survey of world religious traditions, made with Pew.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "humanities",
    subject: "Religion & Mythology",
  },
  "world-mythology": {
    displayName: "World Mythology",
    description: "Crash Course World Mythology: myths, legends, and how cultures explain the world.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "humanities",
    subject: "Religion & Mythology",
  },
  "yale-death": {
    displayName: "Death",
    description: "Yale's landmark course on mortality, taught by Shelly Kagan: whether death is bad, whether we survive it, and how it should shape how we live.",
    type: "course",
    ordered: true,
    source: "Yale (YaleCourses)",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "humanities",
    subject: "Philosophy",
  },

  // --- Sciences ---
  "physics-fundamental": {
    displayName: "Physics in the Wild",
    description: "Veritasium's hand-picked deep dives into the physics and math hiding in everyday phenomena.",
    type: "course",
    ordered: false,
    source: "Veritasium",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "sciences",
    subject: "Physics",
  },
  physics: {
    displayName: "Physics",
    description: "Crash Course Physics: mechanics, energy, and the rules that govern matter.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "sciences",
    subject: "Physics",
  },
  "classical-mechanics-mit": {
    displayName: "Classical Mechanics",
    description: "MIT 8.01SC: the full undergraduate classical mechanics course, lectures and problem-solving included.",
    type: "course",
    ordered: true,
    source: "MIT OpenCourseWare",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "sciences",
    subject: "Physics",
  },
  biology: {
    displayName: "Biology",
    description: "The Amoeba Sisters' Biology Learning Playlist: short, accessible animated lessons.",
    type: "course",
    ordered: true,
    source: "Amoeba Sisters",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "sciences",
    subject: "Biology",
  },
  "biology-crashcourse": {
    displayName: "Biology",
    description: "Crash Course Biology: cells, genetics, ecology, and the systems that make life work.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "sciences",
    subject: "Biology",
  },
  chemistry: {
    displayName: "Chemistry",
    description: "Crash Course Chemistry: atoms, reactions, and the logic of the periodic table.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "sciences",
    subject: "Chemistry",
  },
  "organic-chemistry": {
    displayName: "Organic Chemistry",
    description: "Crash Course Organic Chemistry: carbon-based molecules, reactions, and mechanisms.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "sciences",
    subject: "Chemistry",
  },
  astronomy: {
    displayName: "Astronomy",
    description: "Crash Course Astronomy: the solar system, stars, and the scale of the universe.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "sciences",
    subject: "Earth & Space",
  },
  "spacetime-explainers": {
    displayName: "Space, Time & the Cosmos",
    description: "PBS Space Time's hand-picked deep dives into cosmology, quantum physics, and black holes.",
    type: "course",
    ordered: false,
    source: "PBS Space Time",
    region: ["us", "global"],
    language: "en",
    tier: "advanced",
    department: "sciences",
    subject: "Earth & Space",
  },
  "dhruv-rathee-science": {
    displayName: "Science & Technology (Hindi)",
    description: "Dhruv Rathee's Hindi-language explainers on science, space, and technology, from de-extinction to AI.",
    type: "course",
    ordered: false,
    source: "Dhruv Rathee",
    region: ["in", "global"],
    language: "hi",
    tier: "standard",
    department: "sciences",
    subject: "Science & Technology",
  },

  // --- STEM / Engineering & Tech ---
  "how-things-work": {
    displayName: "How Things Work",
    description: "Curated 3D-animated engineering explainers from Branch Education.",
    type: "course",
    ordered: false,
    source: "Branch Education",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "stem",
    subject: "Engineering",
  },
  "engineering-fundamentals": {
    displayName: "Infrastructure Explained",
    description: "Practical Engineering's hand-picked deep dives into the infrastructure that quietly keeps the world running.",
    type: "course",
    ordered: false,
    source: "Practical Engineering",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "stem",
    subject: "Engineering",
  },
  "computer-science": {
    displayName: "Computer Science",
    description: "Crash Course Computer Science: from logic gates to the modern internet.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "stem",
    subject: "Computer Science",
  },
  "intro-cs-mit": {
    displayName: "Intro to CS and Programming",
    description: "MIT 6.100L: a rigorous, from-scratch introduction to computer science and Python programming.",
    type: "course",
    ordered: true,
    source: "MIT OpenCourseWare",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "stem",
    subject: "Computer Science",
  },
  "linear-algebra": {
    displayName: "Essence of Linear Algebra",
    description: "3Blue1Brown's visual, intuition-first tour of linear algebra.",
    type: "course",
    ordered: true,
    source: "3Blue1Brown",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "stem",
    subject: "Mathematics",
  },
  statistics: {
    displayName: "Statistics",
    description: "Crash Course Statistics: how data is collected, summarized, and (mis)used to make arguments.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "stem",
    subject: "Mathematics",
  },
  "number-curiosities": {
    displayName: "Number Curiosities",
    description: "Numberphile's hand-picked tour of the strange, elegant ideas hiding in numbers and puzzles.",
    type: "course",
    ordered: false,
    source: "Numberphile",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "stem",
    subject: "Mathematics",
  },

  // --- Society & Civics ---
  "cgp-grey": {
    displayName: "How Politics & Systems Really Work",
    description: "CGP Grey's hand-picked explainers on voting systems, institutions, and the rules that govern how power actually works.",
    type: "course",
    ordered: false,
    source: "CGP Grey",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "society-civics",
    subject: "Politics & Society",
  },
  economics: {
    displayName: "Economics",
    description: "Crash Course Economics: markets, incentives, and how economies actually work.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "society-civics",
    subject: "Economics",
  },
  "financial-markets-yale": {
    displayName: "Financial Markets",
    description: "Yale's Financial Markets (2011), taught by Robert Shiller: how markets, risk, and institutions actually work.",
    type: "course",
    ordered: true,
    source: "Yale (YaleCourses)",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "society-civics",
    subject: "Economics",
  },
  "economics-explained": {
    displayName: "Economics Explained",
    description: "Country-by-country economic case studies: what makes economies boom, stagnate, or collapse.",
    type: "course",
    ordered: false,
    source: "Economics Explained",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "society-civics",
    subject: "Economics",
  },
  "government-politics": {
    displayName: "U.S. Government and Politics",
    description: "Crash Course Government and Politics: how the American system actually functions.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["us"],
    language: "en",
    tier: "standard",
    department: "society-civics",
    subject: "Government & Law",
  },
  "moral-foundations-politics": {
    displayName: "Moral Foundations of Politics",
    description: "Yale's Moral Foundations of Politics, taught by Ian Shapiro: the competing theories that justify how we're governed.",
    type: "course",
    ordered: true,
    source: "Yale (YaleCourses)",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "society-civics",
    subject: "Government & Law",
  },
  "justice-sandel": {
    displayName: "Justice",
    description: "Harvard's Justice, taught by Michael Sandel: rights, liberty, and competing theories of what we owe each other.",
    type: "course",
    ordered: true,
    source: "Harvard University",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "society-civics",
    subject: "Government & Law",
  },
  geography: {
    displayName: "Geography",
    description: "Crash Course Geography: physical and human geography, from maps to migration.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "society-civics",
    subject: "Geography",
  },
  "wendover-geography": {
    displayName: "Geopolitics of Geography",
    description: "Wendover Productions on why countries, cities, and borders are where they are, and what that costs.",
    type: "course",
    ordered: false,
    source: "Wendover Productions",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "society-civics",
    subject: "Geography",
  },
  psychology: {
    displayName: "Psychology",
    description: "Crash Course Psychology: the biological and cognitive basis of thought, behavior, and perception.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "society-civics",
    subject: "Psychology",
  },
  "dhruv-rathee-geopolitics": {
    displayName: "Geopolitics Explained (Hindi)",
    description: "Dhruv Rathee's Hindi-language explainers on world conflicts, power struggles, and the forces shaping global politics.",
    type: "course",
    ordered: false,
    source: "Dhruv Rathee",
    region: ["in", "global"],
    language: "hi",
    tier: "standard",
    department: "society-civics",
    subject: "Geopolitics",
  },
  "human-behavioral-biology": {
    displayName: "Human Behavioral Biology",
    description: "Robert Sapolsky's legendary Stanford lecture course on the biology behind behavior.",
    type: "course",
    ordered: true,
    source: "Stanford",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "society-civics",
    subject: "Psychology",
  },

  // --- Arts & Culture ---
  "great-art-explained": {
    displayName: "Great Art Explained",
    description: "James Payne breaks down one famous artwork at a time, clearly and jargon-free, in about 15 minutes.",
    type: "course",
    ordered: false,
    source: "Great Art Explained",
    region: ["global"],
    language: "en",
    tier: "fundamental",
    department: "arts-culture",
    subject: "Art History",
  },
  "art-history": {
    displayName: "Art History",
    description: "Crash Course Art History: how to actually look at, and think about, art.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "arts-culture",
    subject: "Art History",
  },
  "film-history": {
    displayName: "Film History",
    description: "Crash Course Film History: the evolution of cinema as an art form.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "arts-culture",
    subject: "Film",
  },
  "music-theory": {
    displayName: "Music Theory Deep Dives",
    description: "12tone's animated breakdowns of music theory and song analysis.",
    type: "course",
    ordered: false,
    source: "12tone",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "arts-culture",
    subject: "Music",
  },
  "every-frame-a-painting": {
    displayName: "Every Frame a Painting",
    description: "Tony Zhou and Taylor Ramos's complete, pioneering video-essay series on film editing, form, and craft.",
    type: "course",
    ordered: false,
    source: "Every Frame a Painting",
    region: ["global"],
    language: "en",
    tier: "expert",
    department: "arts-culture",
    subject: "Film",
  },

  // --- Media & Information Literacy ---
  "above-the-noise": {
    displayName: "Above The Noise",
    description: "KQED's award-winning series unpacking the research behind misinformation, algorithms, and online manipulation.",
    type: "course",
    ordered: false,
    source: "Above The Noise",
    region: ["us", "global"],
    language: "en",
    tier: "fundamental",
    department: "media-literacy",
    subject: "Critical Thinking",
  },
  "navigating-digital-information": {
    displayName: "Navigating Digital Information",
    description: "Crash Course's guide to evaluating sources and thinking critically online, made with Poynter and Stanford.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "media-literacy",
    subject: "Critical Thinking",
  },
  "media-literacy": {
    displayName: "Media Literacy",
    description: "Crash Course Media Literacy: how journalism works, and how to tell the real thing from its imitators.",
    type: "course",
    ordered: true,
    source: "CrashCourse",
    region: ["global"],
    language: "en",
    tier: "standard",
    department: "media-literacy",
    subject: "Journalism & Research",
  },
  "investigative-journalism": {
    displayName: "Investigative Journalism",
    description: "ICIJ's landmark cross-border investigations, from the Panama Papers and beyond, hand-picked from their real reporting.",
    type: "course",
    ordered: false,
    source: "ICIJ",
    region: ["global"],
    language: "en",
    tier: "advanced",
    department: "media-literacy",
    subject: "Journalism & Research",
  },
  "retro-report-in-pursuit": {
    displayName: "In Pursuit",
    description: "Retro Report's Emmy-winning investigative series connecting today's news to the historical record other outlets skip.",
    type: "course",
    ordered: false,
    source: "Retro Report",
    region: ["us", "global"],
    language: "en",
    tier: "expert",
    department: "media-literacy",
    subject: "Journalism & Research",
  },

  // --- Extracurricular ---
  "chess-openings": {
    displayName: "Chess Openings",
    description: "GothamChess's rundown of the openings every player should know.",
    type: "course",
    ordered: false,
    source: "GothamChess",
    region: ["global"],
    language: "en",
    tier: "extracurricular",
    department: "games-strategy",
    subject: "Chess",
  },
  "game-theory": {
    displayName: "Game Theory: Best Of",
    description: "MatPat's Game Theorists dig into the lore, design, and hidden logic behind your favorite video games.",
    type: "course",
    ordered: false,
    source: "The Game Theorists",
    region: ["us", "global"],
    language: "en",
    tier: "extracurricular",
    department: "games-strategy",
    subject: "Gaming Lore & Theory",
  },
  "everyday-tech": {
    displayName: "Everyday Tech, Explained",
    description: "Technology Connections' deep dives into the mundane technology you use every day.",
    type: "course",
    ordered: false,
    source: "Technology Connections",
    region: ["us", "global"],
    language: "en",
    tier: "extracurricular",
    department: "tech-curiosities",
    subject: "Everyday Tech",
  },
  nilered: {
    displayName: "Chemistry, But Fun",
    description: "NileRed's real chemistry syntheses and demonstrations, done for the sheer spectacle of it.",
    type: "course",
    ordered: false,
    source: "NileRed",
    region: ["global"],
    language: "en",
    tier: "extracurricular",
    department: "tech-curiosities",
    subject: "Chemistry Demonstrations",
  },
  "countries-az": {
    displayName: "Countries A-Z",
    description: "Geography Now's complete country-by-country tour of the world.",
    type: "course",
    ordered: true,
    source: "Geography Now",
    region: ["global"],
    language: "en",
    tier: "extracurricular",
    department: "places-culture",
    subject: "World Geography",
  },
  "home-cooking": {
    displayName: "But Cheaper",
    description: "Joshua Weissman recreates famous foods for less, using real technique, not just recipes.",
    type: "course",
    ordered: false,
    source: "Joshua Weissman",
    region: ["us", "global"],
    language: "en",
    tier: "extracurricular",
    department: "food-culture",
    subject: "Home Cooking",
  },
  "otr-food-history": {
    displayName: "Food & History",
    description: "OTR digs into the history and culture behind dishes and ingredients, where food's stories are people's stories.",
    type: "course",
    ordered: false,
    source: "OTR Food & History",
    region: ["global"],
    language: "en",
    tier: "extracurricular",
    department: "food-culture",
    subject: "Food History",
  },
  blacksmithing: {
    displayName: "Blacksmithing Projects",
    description: "Alec Steele's hands-on bladesmithing and blacksmithing project videos.",
    type: "course",
    ordered: false,
    source: "Alec Steele",
    region: ["eu", "global"],
    language: "en",
    tier: "extracurricular",
    department: "life-skills-making",
    subject: "Craft & Metalworking",
  },
  "colin-furze": {
    displayName: "Mad Inventions",
    description: "Colin Furze builds the most over-the-top, backyard-workshop inventions on the internet.",
    type: "course",
    ordered: false,
    source: "Colin Furze",
    region: ["eu", "global"],
    language: "en",
    tier: "extracurricular",
    department: "life-skills-making",
    subject: "Mad Inventions",
  },
  "personal-finance": {
    displayName: "Money Basics",
    description: "Two Cents (PBS Digital Studios) on budgeting, saving, debt, and investing, without the hype.",
    type: "course",
    ordered: false,
    source: "Two Cents",
    region: ["us", "global"],
    language: "en",
    tier: "extracurricular",
    department: "money-finance",
    subject: "Personal Finance",
  },
  "ben-felix-investing": {
    displayName: "Investing, Evidence-Based",
    description: "Ben Felix on what the actual research says about investing, retirement, and the personal-finance advice everyone repeats.",
    type: "course",
    ordered: false,
    source: "Ben Felix",
    region: ["global"],
    language: "en",
    tier: "extracurricular",
    department: "money-finance",
    subject: "Investing & Personal Finance",
  },

  // --- Entertainment ---
  "dude-perfect": {
    displayName: "Trick Shots",
    description: "Dude Perfect's trick-shot spectacles, pure fun and zero pretense.",
    type: "course",
    ordered: false,
    source: "Dude Perfect",
    region: ["us", "global"],
    language: "en",
    tier: "entertainment",
    department: "sports-stunts",
    subject: "Trick Shots",
  },
  "people-are-awesome": {
    displayName: "Amazing Feats",
    description: "People Are Awesome's best-of compilations of extreme sports, stunts, and jaw-dropping physical skill.",
    type: "course",
    ordered: false,
    source: "People Are Awesome",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "sports-stunts",
    subject: "Extreme Sports & Skill",
  },
  "key-and-peele": {
    displayName: "Key & Peele",
    description: "Keegan-Michael Key and Jordan Peele's Emmy-winning sketch comedy, from Obama's Anger Translator to the East/West Bowl.",
    type: "course",
    ordered: false,
    source: "Key & Peele",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "comedy",
    subject: "Sketch Comedy",
  },
  "biswa-kalyan-rath": {
    displayName: "Stand-Up, Biswa Kalyan Rath",
    description: "Observational stand-up from one of India's sharpest comedians, story-driven and dry.",
    type: "course",
    ordered: false,
    source: "Biswa Kalyan Rath",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "comedy",
    subject: "Stand-Up Comedy",
  },
  "travel-immersion": {
    displayName: "Immersive Travel",
    description: "Peter Santenello's deep, unscripted immersion in specific places and communities.",
    type: "course",
    ordered: false,
    source: "Peter Santenello",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "travel-adventure",
    subject: "Immersive Travel",
  },
  "people-profiles-bios": {
    displayName: "Biographies",
    description: "The People Profiles' historian-scripted biographical documentaries.",
    type: "course",
    ordered: false,
    source: "The People Profiles",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "documentaries",
    subject: "Biography",
  },
  "timeline-documentaries": {
    displayName: "World History Documentaries",
    description: "Timeline's licensed, full-length history documentaries, from ancient civilizations to the Cold War.",
    type: "course",
    ordered: false,
    source: "Timeline",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "documentaries",
    subject: "World History Documentaries",
  },
  "great-big-story": {
    displayName: "Amazing Humans",
    description: "Great Big Story's short, quirky, wholehearted mini-docs on the wonderfully specific people who make the world weirder and better.",
    type: "course",
    ordered: false,
    source: "Great Big Story",
    region: ["us", "global"],
    language: "en",
    tier: "entertainment",
    department: "documentaries",
    subject: "Human Interest Stories",
  },
  "omeleto-shorts": {
    displayName: "Award-Winning Shorts",
    description: "Omeleto's curated selection of award-recognized short films across genres.",
    type: "course",
    ordered: false,
    source: "Omeleto",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "short-films",
    subject: "Short Films",
  },
  "dust-shorts": {
    displayName: "Sci-Fi Shorts",
    description: "DUST's curated short science fiction films: independent, thought-provoking, one story at a time.",
    type: "course",
    ordered: false,
    source: "DUST",
    region: ["global"],
    language: "en",
    tier: "entertainment",
    department: "short-films",
    subject: "Science Fiction",
  },

  // --- Miscellaneous ---
  "lex-fridman-podcast": {
    displayName: "Lex Fridman Podcast",
    description: "Long-form conversations on AI, technology, philosophy, and science.",
    type: "course",
    ordered: false,
    source: "Lex Fridman",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "podcasts-conversations",
    subject: "AI, Tech & Philosophy",
  },
  "conan-needs-a-friend": {
    displayName: "Conan O'Brien Needs A Friend",
    description: "Conan's full-episode celebrity interview podcast: genuinely funny, nothing to learn, no notes to take.",
    type: "course",
    ordered: false,
    source: "Team Coco",
    region: ["us", "global"],
    language: "en",
    tier: "miscellaneous",
    department: "podcasts-conversations",
    subject: "Comedy & Interviews",
  },
  "lemmino-mysteries": {
    displayName: "Mysteries & Investigations",
    description: "LEMMiNO's meticulously researched long-form video essays on unsolved cases and hidden history.",
    type: "course",
    ordered: false,
    source: "LEMMiNO",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "storytelling",
    subject: "Mysteries & Investigations",
  },
  esoterica: {
    displayName: "Esoterica",
    description: "Dr. Justin Sledge's deep-dives into ancient religion, Gnosticism, and the history of magic and alchemy.",
    type: "course",
    ordered: false,
    source: "Esoterica",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "storytelling",
    subject: "History, Philosophy & Religion",
  },
  "yc-startup-talks": {
    displayName: "Startup Lessons",
    description: "Y Combinator's founder talks, fundraising guidance, and scaling frameworks.",
    type: "course",
    ordered: false,
    source: "Y Combinator",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "business-startups",
    subject: "Startup Lessons",
  },
  "company-man-business": {
    displayName: "Company Case Studies",
    description: "Company Man breaks down the rise, fall, and strategy behind well-known businesses.",
    type: "course",
    ordered: false,
    source: "Company Man",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "business-startups",
    subject: "Company History",
  },

  // --- Miscellaneous: Health & Wellness ---
  "tara-brach-meditation": {
    displayName: "Meditation & Emotional Healing",
    description: "Tara Brach, clinical psychologist and Buddhist meditation teacher, on mindfulness, self-compassion, and working with difficult emotions.",
    type: "course",
    ordered: false,
    source: "Tara Brach",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "health-wellness",
    subject: "Meditation",
  },
  "jeff-nippard-exercise": {
    displayName: "Exercise Science",
    description: "Jeff Nippard on what the research actually says about training, muscle growth, and recovery, no bro-science.",
    type: "course",
    ordered: false,
    source: "Jeff Nippard",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "health-wellness",
    subject: "Exercise Science",
  },
  "abbey-sharp-nutrition": {
    displayName: "Nutrition, Fact-Checked",
    description: "Registered Dietitian Abbey Sharp debunks diet trends and breaks down what's actually backed by nutrition science.",
    type: "course",
    ordered: false,
    source: "Abbey Sharp",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "health-wellness",
    subject: "Nutrition",
  },
  "therapy-in-a-nutshell": {
    displayName: "Understanding Mental Health",
    description: "Licensed therapist Emma McAdam on anxiety, depression, and practical, evidence-based emotional-regulation skills.",
    type: "course",
    ordered: false,
    source: "Therapy in a Nutshell",
    region: ["global"],
    language: "en",
    tier: "miscellaneous",
    department: "health-wellness",
    subject: "Mental Health",
  },
};
